// Real South Zone Trainers Database extracted from the attached spreadsheet

export interface RawTrainer {
  name: string;
  email: string;
  city: string;
  state: string;
  team_leader: string;
  phone: string;
  employee_code: string;
  language: string;
  address?: string;
  pin?: string | number;
}

export const CITY_COORDS: Record<string, { lat: number; lng: number }> = {
  "Bangalore": { lat: 12.9716, lng: 77.5946 },
  "Chennai": { lat: 13.0827, lng: 80.2707 },
  "Chromepet": { lat: 12.9463, lng: 80.1400 },
  "Trivandrum": { lat: 8.5241, lng: 76.9366 },
  "Visakhapatnam": { lat: 17.6868, lng: 83.2185 },
  "Hyderabad": { lat: 17.3850, lng: 78.4867 },
  "Coimbatore": { lat: 11.0168, lng: 76.9558 },
  "Vijayawada": { lat: 16.5062, lng: 80.6480 },
  "Madurai": { lat: 9.9252, lng: 78.1198 },
  "Pondicherry": { lat: 11.9416, lng: 79.8083 },
  "Hubli": { lat: 15.3647, lng: 75.1240 },
  "Kannur": { lat: 11.8745, lng: 75.3704 },
  "Thrissur": { lat: 10.5276, lng: 76.2144 },
  "Trichy": { lat: 10.7905, lng: 78.7047 },
  "Kurnool": { lat: 15.8281, lng: 78.0373 },
  "Rajamahendravaram": { lat: 17.0005, lng: 81.8016 },
  "Mangalore": { lat: 12.9141, lng: 74.8560 },
  "Guntur": { lat: 16.3067, lng: 80.4365 },
  "Alappuzha": { lat: 9.4981, lng: 76.3388 },
  "Tirupathi": { lat: 13.6284, lng: 79.4192 },
  "Karimnagar": { lat: 18.4386, lng: 79.1288 },
  "Hosur": { lat: 12.7409, lng: 77.8253 },
  "Kozhikode": { lat: 11.2588, lng: 75.7804 },
  "Belgaum": { lat: 15.8497, lng: 74.4977 },
  "Kalaburagi": { lat: 17.3297, lng: 76.8343 },
  "Nellore": { lat: 14.4426, lng: 79.9865 },
  "Ongole": { lat: 15.5057, lng: 80.0499 },
  "Davanagere": { lat: 14.4644, lng: 75.9218 },
  "Kollam": { lat: 8.8932, lng: 76.6141 },
  "Vellore": { lat: 12.9165, lng: 79.1325 },
  "Kottayam": { lat: 9.5916, lng: 76.5221 },
  "Anantapur": { lat: 14.6819, lng: 77.6006 },
  "Kasaragod": { lat: 12.5103, lng: 74.9852 },
  "Mysore": { lat: 12.2958, lng: 76.6394 },
  "Sangareddy": { lat: 17.6139, lng: 78.0816 },
  "Tirupattur": { lat: 12.4934, lng: 78.5639 }
};

export const RAW_SOUTH_ZONE_TRAINERS: RawTrainer[] = [
  {
    name: "Abhishek B N",
    email: "abhishek.bn@petpooja.com",
    city: "Bangalore",
    state: "Karnataka",
    team_leader: "Abdus Salam",
    phone: "8155096622",
    employee_code: "PJ-KA-101",
    language: "Kannada"
  },
  {
    name: "Abdus Salam",
    email: "abdus.salam@petpooja.com",
    city: "Chennai",
    state: "Tamil Nadu",
    team_leader: "Abdus Salam",
    phone: "8155096665",
    employee_code: "PJ-TN-102",
    language: "Tamil"
  },
  {
    name: "Rajkumar R.",
    email: "rajkumar.r@petpooja.com",
    city: "Trivandrum",
    state: "Kerala",
    team_leader: "Abdus Salam",
    phone: "6357238486",
    employee_code: "PJ-KL-103",
    language: "Malayalam"
  },
  {
    name: "Chidamana Jaya Chandraraman",
    email: "jaya.chandraraman@petpooja.com",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    team_leader: "Rahul Shetty",
    phone: "7227891994",
    employee_code: "PJ-AP-104",
    language: "Telugu"
  },
  {
    name: "Akhil Srinivas",
    email: "akhil.srinivas@petpooja.com",
    city: "Hyderabad",
    state: "Telangana",
    team_leader: "Rahul Shetty",
    phone: "8155096600",
    employee_code: "PJ-TS-105",
    language: "Telugu"
  },
  {
    name: "Vanaraja S",
    email: "vanaraja.s@petpooja.com",
    city: "Chromepet",
    state: "Tamil Nadu",
    team_leader: "Manoj P",
    phone: "6357191969",
    employee_code: "PJ-TN-106",
    language: "Tamil"
  },
  {
    name: "Manoj P",
    email: "manoj.p@petpooja.com",
    city: "Coimbatore",
    state: "Tamil Nadu",
    team_leader: "Abdus Salam",
    phone: "7486018918",
    employee_code: "PJ-TN-107",
    language: "Tamil"
  },
  {
    name: "Mohd Abdullah",
    email: "mohd.abdullah@petpooja.com",
    city: "Hyderabad",
    state: "Telangana",
    team_leader: "Abdus Salam",
    phone: "7486018923",
    employee_code: "PJ-TS-108",
    language: "Telugu"
  },
  {
    name: "Prathipati Rakesh",
    email: "rakesh.prathipati@petpooja.com",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    team_leader: "Chidamana Jaya Chandraraman",
    phone: "6353405855",
    employee_code: "PJ-AP-109",
    language: "Telugu"
  },
  {
    name: "Pandiarajan Balasubramani",
    email: "pandiarajan.balasubramani@petpooja.com",
    city: "Madurai",
    state: "Tamil Nadu",
    team_leader: "Manoj P",
    phone: "6353711583",
    employee_code: "PJ-TN-110",
    language: "Tamil"
  },
  {
    name: "Rangaraj O",
    email: "rangaraj.o@petpooja.com",
    city: "Pondicherry",
    state: "Tamil Nadu",
    team_leader: "Manoj P",
    phone: "6358897168",
    employee_code: "PJ-TN-111",
    language: "Tamil"
  },
  {
    name: "Chilakala Rohith",
    email: "rohith.chilakala@petpooja.com",
    city: "Hyderabad",
    state: "Telangana",
    team_leader: "Akhil Srinivas",
    phone: "8155096644",
    employee_code: "PJ-TS-112",
    language: "Telugu"
  },
  {
    name: "Pradeep Dhongadi",
    email: "pradeep.dhongadi@petpooja.com",
    city: "Hubli",
    state: "Karnataka",
    team_leader: "Abhishek B N",
    phone: "6358919946",
    employee_code: "PJ-KA-113",
    language: "Kannada"
  },
  {
    name: "Harith Sreedhar",
    email: "harith.shreedhar@petpooja.com",
    city: "Kannur",
    state: "Kerala",
    team_leader: "Rajkumar R.",
    phone: "6358916500",
    employee_code: "PJ-KL-114",
    language: "Malayalam"
  },
  {
    name: "Nikson P P",
    email: "nikson.pp@petpooja.com",
    city: "Thrissur",
    state: "Kerala",
    team_leader: "Rajkumar R.",
    phone: "6358919914",
    employee_code: "PJ-KL-115",
    language: "Malayalam"
  },
  {
    name: "Sakthivel C",
    email: "c.sakthivel@petpooja.com",
    city: "Trichy",
    state: "Tamil Nadu",
    team_leader: "Manoj P",
    phone: "7486040772",
    employee_code: "PJ-TN-116",
    language: "Tamil"
  },
  {
    name: "Karthik Mani",
    email: "karthik.mani@petpooja.com",
    city: "Chennai",
    state: "Tamil Nadu",
    team_leader: "Manoj P",
    phone: "6351305643",
    employee_code: "PJ-TN-117",
    language: "Tamil"
  },
  {
    name: "Sathish Kumar G",
    email: "sathish.g@petpooja.com",
    city: "Bangalore",
    state: "Karnataka",
    team_leader: "Abhishek B N",
    phone: "6358915968",
    employee_code: "PJ-KA-118",
    language: "Kannada / Tamil"
  },
  {
    name: "J Sai Charan Teja",
    address: "76-97-413GF, Wearker Section Colony, Kallur, Kurnool.",
    pin: "518003",
    city: "Kurnool",
    state: "Andhra Pradesh",
    team_leader: "Chidamana Jaya Chandraraman",
    email: "sai.teja@petpooja.com",
    language: "Telugu",
    employee_code: "PJ-AP-119",
    phone: "6353952325"
  },
  {
    name: "Rajesh pallela",
    address: "8-2/27, murali nagar, Gokavaram,East Godavari District, Andhra Pradesh",
    pin: "533286",
    city: "Rajamahendravaram",
    state: "Andhra Pradesh",
    team_leader: "Chidamana Jaya Chandraraman",
    email: "sai.pallela@petpooja.com",
    language: "Telugu, English",
    employee_code: "PJ-AP-120",
    phone: "6353074595"
  },
  {
    name: "Sujay Keshav Athri",
    address: "#1 201, blue gate, deadend house, opp to varthur govt college, road between hitech furnitures and ali key makers Varthur- 560087 bengaluru",
    pin: "560087",
    city: "Bangalore",
    state: "Karnataka",
    team_leader: "Abhishek B N",
    email: "sujay.athri@petpooja.com",
    language: "Kannada",
    employee_code: "PJ-KA-121",
    phone: "7486018904"
  },
  {
    name: "Chandrashekhara",
    address: "Near H Q Nagari,Maroli, Mangaluru",
    pin: "575007",
    city: "Mangalore",
    state: "Karnataka",
    team_leader: "Abhishek B N",
    email: "chandrashekhara.d@petpooja.com",
    language: "Kannada",
    employee_code: "PJ-KA-122",
    phone: "6357238489"
  },
  {
    name: "Kishore Kumar",
    address: "82/2a, Kattunayan nagar, pothur main road, redhills, chennai",
    pin: "600054",
    city: "Chennai",
    state: "Tamil Nadu",
    team_leader: "Manoj P",
    email: "kishore.kumar@petpooja.com",
    language: "Tamil , English",
    employee_code: "PJ-TN-123",
    phone: "6353406443"
  },
  {
    name: "Shaikh Umarlisha",
    address: "Flat no 504, Pranathi Heavens, Duvvada, Rajeev Nagar Road, Kurmanapalem, Gajuwaka, 530046",
    pin: "530046",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    team_leader: "Chidamana Jaya Chandraraman",
    email: "umarlisha.shaikh@petpooja.com",
    language: "Telugu , English",
    employee_code: "PJ-AP-124",
    phone: "6358929988"
  },
  {
    name: "Shakthi balaji",
    address: "22, Thangam Colony 2nd St, Tirumular Colony, Sector H, Anna Nagar, Chennai, Tamil Nadu 600038",
    pin: "600038",
    city: "Chennai",
    state: "Tamil Nadu",
    team_leader: "Manoj P",
    email: "shakthi.balaji@petpooja.com",
    language: "Tamil",
    employee_code: "PJ-TN-125",
    phone: "8155096125"
  },
  {
    name: "Pavan Kumar M",
    address: "NO 23, 3rd cross, Bangalore English school road Near HDFC ATM,Naganathapura, Bangalore 560100",
    pin: "560100",
    city: "Bangalore",
    state: "Karnataka",
    team_leader: "Abhishek BN",
    email: "pavan.m@petpooja.com",
    language: "Kannada",
    employee_code: "PJ-KA-126",
    phone: "9558917992"
  },
  {
    name: "Shahul Syed",
    address: "D.No:78-5-392, Near Nookalamma Temple, Behind St.Patrick's School,Lalapet,Guntur-522003, Andhra Pradesh.",
    pin: "522003",
    city: "Guntur",
    state: "Andhra Pradesh",
    team_leader: "Chidamana Jaya Chandraraman",
    email: "shahul.syed@petpooja.com",
    language: "Telugu",
    employee_code: "PJ-AP-127",
    phone: "7041231618"
  },
  {
    name: "shaik Afsar",
    address: "9-4-136/34/A, Abdullah building, Quli Qutub shah nagar, Tolichowki , Hyderabad 500008 , Above the, Dry clean shop ( Istari ki dukan ) near to irfan kirana store",
    pin: "500008",
    city: "Hyderabad",
    state: "Telangana",
    team_leader: "Akhil Srinivas",
    email: "afsar.shaik@gmail.com",
    language: "Telugu",
    employee_code: "PJ-TL-128",
    phone: "6353405838"
  },
  {
    name: "Salman salim",
    address: "Thaiparambil, Aryad South, Avalookkunnu P O, Alappuzha, Kerala, 688006",
    pin: "688006",
    city: "Alappuzha",
    state: "Kerala",
    team_leader: "Rajkumar R",
    email: "salman.salim@petpooja.com",
    language: "Malayalam",
    employee_code: "PJ-KL-129",
    phone: "6358915501"
  },
  {
    name: "Divahar",
    address: "338 Indra Gandhi Street VK Road Peelamedu Coimbatore 641004",
    pin: 641004,
    city: "Coimbatore",
    state: "Tamil Nadu",
    team_leader: "Manoj P",
    email: "divahar.s@petpooja.com",
    language: "Tamil",
    employee_code: "PJ-TN-130",
    phone: "7383887031"
  },
  {
    name: "Chandrashekhar Nelavala",
    address: "Tirupathi",
    pin: "517501",
    city: "Tirupathi",
    state: "Andhra Pradesh",
    team_leader: "Chidamana Jaya Chandraraman",
    email: "chandrasekhar.nelavala@petpooja.com",
    language: "Telugu",
    employee_code: "PJ-AP-131",
    phone: "7041018210"
  },
  {
    name: "Ramesh Dhadi",
    address: "H.No:4-40/1,village:variole,mondal:Koheda,Distict:Siddipet-505530,Telangana",
    pin: "505530",
    city: "Karimnagar",
    state: "Telangana",
    team_leader: "Akhil Srinivas",
    email: "ramesh.dhadi@petpooja.com",
    language: "Telugu",
    employee_code: "PJ-TL-132",
    phone: "9274415236"
  },
  {
    name: "Daveedu",
    address: "Bangalore",
    pin: "560001",
    city: "Bangalore",
    state: "Karnataka",
    team_leader: "Abhishek BN",
    email: "daveedu.a@petpooja.com",
    language: "Kannada",
    employee_code: "PJ-KA-133",
    phone: "7227054996"
  },
  {
    name: "Anil P",
    address: "No 136, Muniwanappa road, JC nagar, BENGALURU, KARNATAKA, 560006, India",
    pin: "560006",
    city: "Bangalore",
    state: "Karnataka",
    team_leader: "Abhishek BN",
    email: "anil.p@petpooja.com",
    language: "tamil,kannada,hindi and english",
    employee_code: "PJ-KA-134",
    phone: "7041367982"
  },
  {
    name: "Ajay",
    address: "Bangalore",
    pin: "560001",
    city: "Bangalore",
    state: "Karnataka",
    team_leader: "Abhishek BN",
    email: "ajay.k@petpooja.com",
    language: "Kannada",
    employee_code: "PJ-KA-135",
    phone: "9104189231"
  },
  {
    name: "Girish",
    address: "40/26, Kennedy sqaure, 1st South street, TVK Nagar, Perambur Chennai-600011",
    pin: "600011",
    city: "Chennai",
    state: "Tamil Nadu",
    team_leader: "Manoj P",
    email: "girishwaran.n@petpooja.com",
    language: "Tamil",
    employee_code: "PJ-TN-136",
    phone: "9173914384"
  },
  {
    name: "Balaji G",
    address: "1/64, Joug Street, Berigai, Hosur, TamilNadu - 635105",
    pin: "635105",
    city: "Hosur",
    state: "Karnataka",
    team_leader: "Abhishek BN",
    email: "balaji.g@petpooja.com",
    language: "Tamil",
    employee_code: "PJ-KA-137",
    phone: "9974003502"
  },
  {
    name: "Shyju",
    address: "Pratheeksha House, Kottakadavu, Kadalundi P O, Kozhikode-673302",
    pin: "673302",
    city: "Kozhikode",
    state: "Kerala",
    team_leader: "Rajkumar R.",
    email: "shyju.v@petpooja.com",
    language: "Malayalam",
    employee_code: "PJ-KL-138",
    phone: "9974007605"
  },
  {
    name: "Karan Uday Mirajkar",
    address: "Seetharapuram, Near sp bungalow Srigiri temple , Ongole",
    pin: "590010",
    city: "Belgaum",
    state: "Karnataka",
    team_leader: "Abhishek BN",
    email: "karan.mirajkar@petpooja.com",
    language: "Kannada",
    employee_code: "PJ-KA-139",
    phone: "6358929775"
  },
  {
    name: "Anand Kumman",
    address: "H.No.8-1545/119/G/1 Kumman Nilaya near nagdev mandir Shivaji Nagar Kalaburagi-585104 Karnataka",
    pin: "585104",
    city: "Kalaburagi",
    state: "Karnataka",
    team_leader: "Abhishek BN",
    email: "anand.kumman@petpooja.com",
    language: "Kannada",
    employee_code: "PJ-KA-140",
    phone: "6358921454"
  },
  {
    name: "KARTIK RAO",
    address: "Agrahara village, Jakkur, Bengaluru, Karnataka 560064",
    pin: "560064",
    city: "Bangalore",
    state: "Karnataka",
    team_leader: "Abhishek BN",
    email: "kartik.rao@petpooja.com",
    language: "Kannada",
    employee_code: "PJ-KA-141",
    phone: "9898885947"
  },
  {
    name: "chaitanya",
    address: "Flat no. 281, 8th Street Nirmal Nagar, Telugu Ganga colony, Nellore,-524004",
    pin: "524004",
    city: "Nellore",
    state: "Andhra Pradesh",
    team_leader: "Chidamana Jaya Chandraraman",
    email: "chaithanya.vandrangi@petpooja.com",
    language: "Telugu / English",
    employee_code: "PJ-AP-142",
    phone: "6358915958"
  },
  {
    name: "Vamsi",
    address: "Seetharapuram, Near sp bungalow Srigiri temple , Ongole",
    pin: "523001",
    city: "Ongole",
    state: "Andhra Pradesh",
    team_leader: "Akhil Srinivas",
    email: "vamsi.motupalli@petpooja.com",
    language: "Telugu / English / Hindi",
    employee_code: "PJ-AP-143",
    phone: "6358921497"
  },
  {
    name: "PRABHAKARAN K",
    address: "11c Balaji Engineering,Eye Hospital Road, Nithya Catrering ,Sivanathapuram Saravanampatti, Coimbatore -641035",
    pin: "641035",
    city: "Coimbatore",
    state: "Tamil Nadu",
    team_leader: "Manoj P",
    email: "prabhakaran.k@petpooja.com",
    language: "Tamil / English",
    employee_code: "PJ-TN-144",
    phone: "6358929739"
  },
  {
    name: "Marimuthu Duraisamy",
    address: "No:19, Ramakrishna St, opposite Bata showroom, West Tambaram, Tambaram, Chennai, Tamil Nadu 600045",
    pin: "600045",
    city: "Chennai",
    state: "Tamil Nadu",
    team_leader: "Manoj P",
    email: "marimuthu.duraisamy@petpooja.com",
    language: "Kannada",
    employee_code: "PJ-TN-145",
    phone: "8946025370"
  },
  {
    name: "muinakhtar",
    address: "1448/1 Near Quba Masjid Ahamd Nagar VTC Davanagere PO - Davanagere 577001",
    pin: "577001",
    city: "Davanagere",
    state: "Karnataka",
    team_leader: "Abhishek BN",
    email: "muinakhtar.devageri@petpooja.com",
    language: "Kannada",
    employee_code: "PJ-KA-146",
    phone: "9974015325"
  },
  {
    name: "Sunil Sudhan",
    address: "O2 Zone Apartment, 16 D1 Thengod, Kakkanad, Kochi, Kerala",
    pin: "682030",
    city: "Cochin",
    state: "Kerala",
    team_leader: "Rajkumar R.",
    email: "sunil.sudhan@petpooja.com",
    language: "Malayalam",
    employee_code: "PJ-KL-147",
    phone: "6358871168"
  },
  {
    name: "Rahumathulla",
    address: "Raseena manzil sh nagar 254 thattamala po kollam pin 691020",
    pin: "691020",
    city: "Kollam",
    state: "Kerala",
    team_leader: "Rajkumar R.",
    email: "rahumathulla.r@petpooja.com",
    language: "Malayalam",
    employee_code: "PJ-KL-148",
    phone: "6358897146"
  },
  {
    name: "Anupam Roy",
    address: "17,5th cross road, Nadamma Layout, Kodichikknahalli, Vakil Marina Layout, Bommanahalli, Bengaluru, Karnataka,560068",
    pin: "560068",
    city: "Bangalore",
    state: "Karnataka",
    team_leader: "Abhishek BN",
    email: "anupam.roy@petpooja.com",
    language: "Hindi / English / Kannada / Bengali",
    employee_code: "PJ-KA-149",
    phone: "7041231499"
  },
  {
    name: "Rajesh R",
    address: "Periyakurumbatheru , Kothakottai po , Vaniyambadi Tk",
    pin: "635752",
    city: "Vellore",
    state: "Tamil Nadu",
    team_leader: "Manoj P",
    email: "rajesh.r@petpooja.com",
    language: "Tamil",
    employee_code: "PJ-TN-150",
    phone: "6358916501"
  },
  {
    name: "Aswin KA",
    address: "Cochin, Kerala",
    pin: "682001",
    city: "Cochin",
    state: "Kerala",
    team_leader: "Rajkumar R.",
    email: "aswin.ka@petpooja.com",
    language: "Malayalam",
    employee_code: "PJ-KL-151",
    phone: "9974028329"
  },
  {
    name: "RIZWAN",
    address: "Puliyorath (H), Vadakara P.O , Thalayolaparambu, Kottayam",
    pin: "686605",
    city: "Kottayam",
    state: "Kerala",
    team_leader: "Rajkumar R.",
    email: "rizwan.pn@petpooja.com",
    language: "Malayalam",
    employee_code: "PJ-KL-152",
    phone: "9974026039"
  },
  {
    name: "SARANG",
    address: "Manathanath(ho), Kuningad(po), Purameri (via), 673503, Kozhikode, Kerala",
    pin: "673503",
    city: "Kozhikode",
    state: "Kerala",
    team_leader: "Rajkumar R.",
    email: "sarang@petpooja.com",
    language: "Malayalam",
    employee_code: "PJ-KL-153",
    phone: "9974026040"
  },
  {
    name: "Anand Kumar Paramasivan",
    address: "No.247, TNHB, Phase - II, Tirupattur - 635601",
    pin: "635601",
    city: "Tirupattur",
    state: "Tamil Nadu",
    team_leader: "Manoj P",
    email: "anand.kumar@petpooja.com",
    language: "Tamil",
    employee_code: "PJ-TN-154",
    phone: "9974026041"
  },
  {
    name: "Pavan Boyapati",
    address: "1-1-957, Indhira Nagar, 2nd road extension, Anantapur - 515001",
    pin: "515001",
    city: "Anantapur",
    state: "Andhra Pradesh",
    team_leader: "Chidamana Jaya Chandraraman",
    email: "pavan.boyapati@petpooja.com",
    language: "English / Telugu",
    employee_code: "PJ-AP-155",
    phone: "9974014754"
  },
  {
    name: "Musthaq Ahmed",
    address: "NO-4 2nd floor Near Wisdom school 1st Main Rd, HBR Layout 2nd Block, Stage 1, HBR Layout, Bengaluru, Karnataka 560043",
    pin: "560043",
    city: "Bangalore",
    state: "Karnataka",
    team_leader: "Abhishek BN",
    email: "mushtaq.ahmed@petpooja.com",
    language: "Kannada / English / Hindi / Tamil",
    employee_code: "PJ-KA-156",
    phone: "9974027086"
  },
  {
    name: "Vijithendra K",
    address: "Anil Kumble Road, near BSNL Telephone Exchange, Kumbla, Kasaragod, Kerala",
    pin: "671321",
    city: "Kasaragod",
    state: "Kerala",
    team_leader: "Rajkumar R.",
    email: "vijithendra.k@petpooja.com",
    language: "Malayalam / Kannada",
    employee_code: "PJ-KL-157",
    phone: "7041018217"
  },
  {
    name: "Shiva K",
    address: "NO 307, 7th Main 10th Cross, Kashinagar, Yelachenahalli, Bangalore South, Bangalore, Karnataka - 560079",
    pin: "560079",
    city: "Bangalore",
    state: "Karnataka",
    team_leader: "Abhishek BN",
    email: "shiva.k@petpooja.com",
    language: "Kannada",
    employee_code: "PJ-KA-158",
    phone: "7043015670"
  },
  {
    name: "Anil Nayaka S",
    address: "#52 4th main 30th Cross vidhyaranyapuram mysuru 570009",
    pin: "570009",
    city: "Mysore",
    state: "Karnataka",
    team_leader: "Abhishek BN",
    email: "anil.nayaka@petpooja.com",
    language: "Kannada / English",
    employee_code: "PJ-KA-159",
    phone: "8155977171"
  },
  {
    name: "Vijay",
    address: "34/2 HMT Main Rd,Gokula 1st Stage,Nanjappa Reddy Colony, Mathikere",
    pin: "560054",
    city: "Bangalore",
    state: "Karnataka",
    team_leader: "Abhishek BN",
    email: "vijay.b@petpooja.com",
    language: "Kannada",
    employee_code: "PJ-KA-160",
    phone: "6357238485"
  },
  {
    name: "Krishna Kumaresan M",
    address: "42/3 Natarajapuram 2nd St,Melapalayam,Tirunelveli-627005",
    pin: "627005",
    city: "Tirunelveli",
    state: "Tamil Nadu",
    team_leader: "Manoj P",
    email: "krishna.kumaresan@petpooja.com",
    language: "Tamil",
    employee_code: "PJ-TN-161",
    phone: "7041017803"
  },
  {
    name: "Pavan Kumar Morangapally",
    address: "H.No. 4-7-23/2/3/3, Adithya Nagar, Bypass Road, Sangareddy, Telangana",
    pin: "502001",
    city: "Sangareddy",
    state: "Telangana",
    team_leader: "Akhil Srinivas",
    email: "pavan.morangapally@petpooja.com",
    language: "Telugu",
    employee_code: "PJ-TS-162",
    phone: "6358897171"
  },
  {
    name: "Sunil P",
    address: "#33 2nd cross DVG layout margondanahalli, Ramamurthy nagar TC palya bangalore 560036",
    pin: "560036",
    city: "Bangalore",
    state: "Karnataka",
    team_leader: "Abhishek BN",
    email: "sunil.p@petpooja.com",
    language: "Kannada / Tamil / English",
    employee_code: "PJ-KA-163",
    phone: "8155981800"
  },
  {
    name: "Marimuthu",
    address: "No:19, Ramakrishna St, opposite Bata showroom, West Tambaram, Tambaram, Chennai, Tamil Nadu",
    pin: "600045",
    city: "Chennai",
    state: "Tamil Nadu",
    team_leader: "Manoj P",
    email: "marimuthu.duraisamy@petpooja.com",
    language: "Tamil / English",
    employee_code: "PJ-TN-164",
    phone: "9974023238"
  },
  {
    name: "srikanth kambhala",
    address: "8-4,543/14/9 B, sankar lal nagar , nataraj nagar , Erragadda , Hyderabad , telengana - 500018",
    pin: "500018",
    city: "Hyderabad",
    state: "Telangana",
    team_leader: "Akhil Srinivas",
    email: "srikanth.kambhala@gmail.com",
    language: "Telugu / English",
    employee_code: "PJ-TS-165",
    phone: "9974025132"
  }
];
